name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ['🛠 goal: fix']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: dropdown
    id: is_regression
    attributes:
      label: Which website is affected?
      description: Please share the website which is having the bug.
      options:
        - "Accessibility First"
        - "Pokedex of Accessibility"
        - "A11y & Inclusion Barcamp Vienna"
        - "The Better Dev"
        - "Julia Undeutsch Linktree"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
